spring.application.name=${APP_NAME:kafka-consumer}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:my-cluster-source-kafka-bootstrap.kafka-source.svc.cluster.local:9092}
kafka.consumer.groupid=${KAFKA_CONSUMER_GROUP_ID:group-id}
kafka.consumer.topic=${KAFKA_TOPIC:topic1}